### ISSUE TITLE
[Question] Handling associated Table

### ISSUE THREAD

**Issue by flashios09** [UseMuffin/Trash#1]
Hi @jadb ,
Thanks for this plugin :+1: 
I have a question, the trash behavior handle only the current table or all his associated tables ?
Let's say that i have a ProductsTable associated with CategoriesTable, if i softDelete a category, their products will be softDeleted or not ?
Thanks

**Comment by jadb** [comment]
I don't think this was added *yet*. 

It needs to read the `dependent` key I guess on the association and only a certain type of association. I don't mind adding it, would just need to scope it well and how it should behave. 

I will keep this open for comments/suggestions and let's see what we come up with to implement real soon.

/cc @ADmad @Phillaf

**Comment by Phillaf** [comment]
Using the ```dependant``` and ```cascadeCallbacks``` options sounds good to me, Unless one of you can forsee a senario where we'd need a different config for ```trash()``` than the one for ```delete()``` ?

**Comment by pedrofs** [comment]
Doesn't `dependent` works at all?

**Comment by davidyell** [comment]
Just came looking for cascading soft delete functionality. I guess we didn't get there yet. Will see what I can turn up today, as I need this 😄

**Comment by davidyell** [comment]
Will need to 
* Recurse through associated table classes and trash related records if `dependent` is true, for specific relationship types, where the primary table class is the owning side of the relationship.
* `trashAll` will need to do the same
* `restoreTrash` will need to invert the above

**Comment by davidyell** [comment]
I've got the cascading trash functionality working, with a test, but I'm struggling to think of a good way to do a cascading undelete in `restoreTrash()`. Any ideas?

**Comment by davidyell** [comment]
I have put together a pull request in #12  which I hope introduces this functionality. I'd welcome insight on the pull request if there are any suggestions.

**Comment by jadb** [comment]
Closing in favour of @davidyell's [PR](https://github.com/UseMuffin/Trash/pull/12).
