### ISSUE TITLE
Produces PDOException on find all in associated models with Trash Behavior

### ISSUE THREAD

**Issue by sourjya** [UseMuffin/Trash#15]
[full-error.log.txt](https://github.com/UseMuffin/Trash/files/561891/full-error.log.txt)
I have 2 model - Tests and Questions. Both are associated with each other using belongsToMany() using a join table.

```
        $this->belongsToMany( 'Questions', [
            'foreignKey'       => 'test_id',
            'targetForeignKey' => 'question_id',
            'joinTable'        => 'tests_questions',
            'through'          => 'TestsQuestions'
        ] );

        $this->belongsToMany( 'Tests', [
            'foreignKey'       => 'question_id',
            'targetForeignKey' => 'test_id',
            'joinTable'        => 'tests_questions',
            'through'          => 'TestsQuestions'
        ] );

```

I've attached Trash Behavior to both the models. 

When I do a paginate in the index function of TestsController, I get the following error:
`Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') IS NULL)' at line 1`

This happens if I "contain" Questions only. (I'm using "friendsofcake/search" plugin - hence the "Search" finder).

```
        // Include search params
        $search = $this->Tests
            // Use the plugins 'search' custom finder and pass in the
            // processed query params
            ->find( 'search', [ 'search' => $this->request->query ] )
            // You can add extra things to the query if you need to
            ->contain( [ 'CreatedBy', 'ModifiedBy', 'Questions' ] );

        $itemsList = $this->paginate( $search );
```

If I take out Questions from the contain list, the error goes away...

```
        // Include search params
        $search = $this->Tests
            // Use the plugins 'search' custom finder and pass in the
            // processed query params
            ->find( 'search', [ 'search' => $this->request->query ] )
            // You can add extra things to the query if you need to
            ->contain( [ 'CreatedBy', 'ModifiedBy ] );

        $itemsList = $this->paginate( $search );
```

Full stacktrace is attached in form of a log file.

Thank you.

**Comment by jadb** [comment]
What is the resulting SQL query you get from debug?
