### ISSUE TITLE
Trash Events

### ISSUE THREAD

**Issue by zalsader** [UseMuffin/Trash#16]
Is it possible to add events before and after trashing, as well as before and after restoration of an entity? That could be helpful in use cases, like when a field should be unique in the database, and we add a postfix to that field, and need to remove it upon restoration.

**Comment by Spriz** [comment]
@zalsader can't you use the existing core cake events?

**Comment by zalsader** [comment]
Well, the before and after delete events will do for trashing, and I could use before and after save when restoring, but I think it would be nicer to have separate events for trashing and restoration, since that will separate it from the rest of the saving logic.

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
