### ISSUE TITLE
Not working with deleteAll()

### ISSUE THREAD

**Issue by doonot** [UseMuffin/Trash#17]
Hi

I was just playing around with the plugin and noticed that soft delete is not applied when the deleteAll() function is used:

`$this->Users->deleteAll(['Users.partner_id' => $id]);`

Is this a bug?

Cheers,
Pat

**Comment by ADmad** [comment]
As stated in the [manual](https://book.cakephp.org/3.0/en/orm/deleting-data.html#bulk-deletes) deleteAll() doesn't trigger callbacks, which are required for this behaviour to do it's job.

**Comment by Spriz** [comment]
@doonot you can use `$this->Users->trashAll()` for this purpose :)
