### ISSUE TITLE
beforeFind() not working correctly, using wrong field

### ISSUE THREAD

**Issue by burzum** [UseMuffin/Trash#32]
My tables field settings:

```php
$this->setDisplayField('title');
$this->setPrimaryKey('id');
````

Inside the trash behaviors beforeFind() there is this code and `$expression->getIdentifier()` returns a totally different field. For whatever reason I'm getting here `'Jobs.contact_first_name'` as field.

```php
        $query->traverseExpressions(function ($expression) use (&$check, $field) {
            if ($expression instanceof IdentifierExpression) {
                !$check && $check = $expression->getIdentifier() === $field;
            }
        });
```

So we still find all jobs, even the deleted ones.

**Comment by ADmad** [comment]
That piece of code traverses all expressions, so finding expressions for fields other than the trash field is not out of the ordinary and hence the check `$expression->getIdentifier() === $field`.

The purpose of the traversal is to not modify the query if it already contains conditions for the trash field. `findWithTrashed()` and `findOnlyTrashed()` wouldn't work if the `beforeFind()` always added condition to exclude trashed fields.

Please provide some example code to reproduce the issue you are having.

**Comment by burzum** [comment]
@ADmad, well I can't simply provide you half of my application. I can copy and paste you the table class if you like to...

**Comment by ADmad** [comment]
Closing as the issue couldn't be reproduced.
