### ISSUE TITLE
New 3.0 stable Release Tag

### ISSUE THREAD

**Issue by JacobAGTyler** [UseMuffin/Trash#45]
Issue #41 is solved by Cake-4-X branch. Please create release tag for branch to indicate stable release.

**Comment by ADmad** [comment]
I was hoping to get some feedback for the `3.0.0-beta` release.

**Comment by JacobAGTyler** [comment]
It can't be used with Cake 4 as the composer.json has Cake3x requirements.

**Comment by ADmad** [comment]
Doh, `3.0.0-beta` was mistakenly tagged off `master` instead of `cake-4.x`. I wish someone would have pointed it out sooner.

**Comment by JacobAGTyler** [comment]
I wondered why it would never work, sorry I should have investigated sooner. :)

**Comment by ADmad** [comment]
`3.0.0-beta2` tagged
