### ISSUE TITLE
Cascade soft deletion does not work on models

### ISSUE THREAD

**Issue by man0l** [UseMuffin/Trash#49]
Hello,
I have 2 models

ContactsTable
CompaniesContactsTable

In CompaniesContactsTable I have a definition of the relation:

`        $this->belongsTo('Contacts');
`

I am trying to set up the relation in ContactsTable

```
        $this->hasMany('CompaniesContacts', [
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);
```

When I delete Contact it doesn't soft delete the dependent CompaniesContacts, the deleted field is null.

Would you advise me how can I solve this issue?

**Comment by ADmad** [comment]
Make sure you have `dependent` and `cascadeCallbacks` options set to `true` for the hasMany association.

**Comment by man0l** [comment]
Hello,
thank you for your reply.

I have enabled the trash behaviour for both `CompaniesContacts ` and `Contacts`.

It is strange because the deleted date in SQL is being set:

![Query](https://user-images.githubusercontent.com/1413216/104921081-891e4080-59a1-11eb-92f4-e8321a5a5dda.png)

I receive a crash as well:

![Error-Error](https://user-images.githubusercontent.com/1413216/104921443-faf68a00-59a1-11eb-9742-571876866ded.png)

**Comment by ADmad** [comment]
You'll have to debug and figure out why the `RuntimeException` is thrown. It seems for some reason the `trash()` is either throwing the exception or returning `false.`

**Comment by man0l** [comment]
The exception was in a build rule in the table class and I managed to fix it. Thank you for your help. @ADmad!
